# Short notebook to splice together the Tynitag csv files

Files are cut everytime you read the logger. In order to present the entire dataseries one needs to combine the files into one single csv file.

## 1. Import required Libraries and Modules

In [1]:
import os
import pandas as pd

# Set working directory
os.chdir('/Users/janoschbeer/Library/Mobile Documents/com~apple~CloudDocs/PhD/projects/asses_swiss_gl_therm_regimes/')

# Import custom modules
from processing.thermistor_processing import *
from calibration.thermistor_chains_icebath_references import *

## 2. Set data and output paths

In [ ]:
# main temperature data path
main_dir = '/Users/janoschbeer/Library/Mobile Documents/com~apple~CloudDocs/PhD/data/fieldwork_data/THERMAP_2024_2025/icetemperature_data/NTC_tynitag/'
temp_path = main_dir + 'temperature_data/'
first_timeseries = '2024/'
second_timeseries = '2024_2025/'

# set output path
output_path = main_dir + 'temperature_data/full_timeseries/'

# Hohsaasgletscher
hohsaas_1st_timeseries = [temp_path + first_timeseries + 'BH5_20240808_20240929.csv', temp_path + first_timeseries + 'BH6_20240808_20240929.csv']
hohsaas_2nd_timeseries = [temp_path + second_timeseries + 'BH5_20240929_20250927.csv', temp_path + second_timeseries + 'BH6_20240929_20250927.csv']

# Chessjengletscher
chessjen_1st_timeseries = [temp_path + first_timeseries + 'BH7_20240809_20240929.csv', temp_path + first_timeseries + 'BH8_20240809_20240929.csv']
chessjen_2nd_timeseries = [temp_path + second_timeseries + 'BH7_20240929_20250808.csv', temp_path + second_timeseries + 'BH8_20240929_20250808.csv']

# Alphubel South
alphubel_1st_timeseries = temp_path + first_timeseries + 'BH10_20240821_20241021.csv'
alphubel_2nd_timeseries = temp_path + second_timeseries + 'BH10_20241021_20250805.csv'
alphubel_3rd_timeseries = temp_path + second_timeseries + 'BH10_20250805_20250916.csv' # 3 readings, borehole 9 read only ones

# Sex Rouge
sex_rouge_1st_timeseries = [temp_path + first_timeseries + 'BH1_20240806_20241019.csv', temp_path + first_timeseries + 'BH2_20240806_20241019.csv']
sex_rouge_2nd_timeseries = [temp_path + second_timeseries + 'BH1_20240930_20250724.csv', temp_path + second_timeseries + 'BH2_20240930_20250724.csv']

# Glacier de Tortin
tortin_1st_timeseries = [temp_path + first_timeseries + 'BH3_20240807_20240930.csv', temp_path + first_timeseries + 'BH4_20240807_20240930.csv']
tortin_2nd_timeseries = [temp_path + second_timeseries + 'BH3_20240939_20250723.csv', temp_path + second_timeseries + 'BH4_20240930_20250723.csv']

# Corvatsch
corvatsch_1st_timeseries = temp_path + first_timeseries + 'BH12_20240828_20241020.csv'
corvatsch_2nd_timeseries = temp_path + second_timeseries + 'BH12_20241123_20250905.csv' # borehole 11 read only ones

# read offsets from ice bath references
offsets_path_TT = main_dir + "calibration_data/all_logger_offsets.csv"
corrected_offsets_TT = pd.read_csv(offsets_path_TT)

## 3. Load borehole data for each borehole and each timeseries & apply 0-deg offsets

In [7]:
## Create ThermistorData objects for each borehole and timeseries

# Hohsaasgletscher
hs1tt_1st = ThermistorData(hohsaas_1st_timeseries[0], delimiter=',') # e.g. hs1tt_1st means Hohsaas borehole 1, Tynitag, first timeseries (08.2024 - 09.2024)
hs2tt_1st = ThermistorData(hohsaas_1st_timeseries[1], delimiter=',')
hs1tt_2nd = ThermistorData(hohsaas_2nd_timeseries[0], delimiter=',')
hs2tt_2nd = ThermistorData(hohsaas_2nd_timeseries[1], delimiter=',')

# Chessjengletscher
cj1tt_1st = ThermistorData(chessjen_1st_timeseries[0], delimiter=',')
cj2tt_1st = ThermistorData(chessjen_1st_timeseries[1], delimiter=',')
cj1tt_2nd = ThermistorData(chessjen_2nd_timeseries[0], delimiter=',')
cj2tt_2nd = ThermistorData(chessjen_2nd_timeseries[1], delimiter=',')

# Alphubel South
ah1tt_1st = ThermistorData(alphubel_1st_timeseries, delimiter=',')
ah1tt_2nd = ThermistorData(alphubel_2nd_timeseries, delimiter=',')
ah1tt_3rd = ThermistorData(alphubel_3rd_timeseries, delimiter=',')

# Sex Rouge
sr1tt_1st = ThermistorData(sex_rouge_1st_timeseries[0], delimiter=',')
sr2tt_1st = ThermistorData(sex_rouge_1st_timeseries[1], delimiter=',')
sr1tt_2nd = ThermistorData(sex_rouge_2nd_timeseries[0], delimiter=',')
sr2tt_2nd = ThermistorData(sex_rouge_2nd_timeseries[1], delimiter=',')

# Glacier de Tortin
gt1tt_1st = ThermistorData(tortin_1st_timeseries[0], delimiter=',')
gt2tt_1st = ThermistorData(tortin_1st_timeseries[1], delimiter=',')
gt1tt_2nd = ThermistorData(tortin_2nd_timeseries[0], delimiter=',')
gt2tt_2nd = ThermistorData(tortin_2nd_timeseries[1], delimiter=',')

# Corvatsch
ct2tt_1st = ThermistorData(corvatsch_1st_timeseries, delimiter=',')
ct2tt_2nd = ThermistorData(corvatsch_2nd_timeseries, delimiter=',')

## Get NTC data with offsets applied

# Hohsaasgletscher
hs1tt_1st_data = hs1tt_1st.get_ntc_data_with_offsets('5', offsets_df=corrected_offsets_TT)
hs2tt_1st_data = hs2tt_1st.get_ntc_data_with_offsets('6', offsets_df=corrected_offsets_TT)
hs1tt_2nd_data = hs1tt_2nd.get_ntc_data_with_offsets('5', offsets_df=corrected_offsets_TT)
hs2tt_2nd_data = hs2tt_2nd.get_ntc_data_with_offsets('6', offsets_df=corrected_offsets_TT)

# Chessjengletscher
cj1tt_1st_data = cj1tt_1st.get_ntc_data_with_offsets('7', offsets_df=corrected_offsets_TT)
cj2tt_1st_data = cj2tt_1st.get_ntc_data_with_offsets('8', offsets_df=corrected_offsets_TT)
cj1tt_2nd_data = cj1tt_2nd.get_ntc_data_with_offsets('7', offsets_df=corrected_offsets_TT)
cj2tt_2nd_data = cj2tt_2nd.get_ntc_data_with_offsets('8', offsets_df=corrected_offsets_TT)

# Alphubel South
ah1tt_1st_data = ah1tt_1st.get_ntc_data_with_offsets('10', offsets_df=corrected_offsets_TT)
ah1tt_2nd_data = ah1tt_2nd.get_ntc_data_with_offsets('10', offsets_df=corrected_offsets_TT)
ah1tt_3rd_data = ah1tt_3rd.get_ntc_data_with_offsets('10', offsets_df=corrected_offsets_TT)

# Sex Rouge
sr1tt_1st_data = sr1tt_1st.get_ntc_data_with_offsets('1', offsets_df=corrected_offsets_TT)
sr2tt_1st_data = sr2tt_1st.get_ntc_data_with_offsets('2', offsets_df=corrected_offsets_TT)
sr1tt_2nd_data = sr1tt_2nd.get_ntc_data_with_offsets('1', offsets_df=corrected_offsets_TT)
sr2tt_2nd_data = sr2tt_2nd.get_ntc_data_with_offsets('2', offsets_df=corrected_offsets_TT)

# Glacier de Tortin
gt1tt_1st_data = gt1tt_1st.get_ntc_data_with_offsets('3', offsets_df=corrected_offsets_TT)
gt2tt_1st_data = gt2tt_1st.get_ntc_data_with_offsets('4', offsets_df=corrected_offsets_TT)
gt1tt_2nd_data = gt1tt_2nd.get_ntc_data_with_offsets('3', offsets_df=corrected_offsets_TT)
gt2tt_2nd_data = gt2tt_2nd.get_ntc_data_with_offsets('4', offsets_df=corrected_offsets_TT)

# Corvatsch
ct2tt_1st_data = ct2tt_1st.get_ntc_data_with_offsets('12', offsets_df=corrected_offsets_TT)
ct2tt_2nd_data = ct2tt_2nd.get_ntc_data_with_offsets('12', offsets_df=corrected_offsets_TT)

In [8]:
ct2tt_1st_data

,Measurement,TIME,Black Probe Temperature,White Probe Temperature
0,1,2024-08-28 13:49:00,-0.003,0.010
1,2,2024-08-28 14:49:00,-0.015,-0.053
2,3,2024-08-28 15:49:00,-0.033,-0.075
3,4,2024-08-28 16:49:00,-0.224,-0.112
4,5,2024-08-28 17:49:00,-0.301,-0.180
...,...,...,...,...
1269,1270,2024-10-20 10:49:00,NaN,-2.841
1270,1271,2024-10-20 11:49:00,NaN,-2.841
1271,1272,2024-10-20 12:49:00,NaN,-2.841
1272,1273,2024-10-20 13:49:00,NaN,-2.841
1273,1274,2024-10-20 14:49:00,NaN,-2.839

In [9]:
hs1tt_2nd_data

,Measurement,TIME,Black Probe Temperature,White Probe Temperature
0,1,2024-09-29 12:52:00,-0.224,-0.990
1,2,2024-09-29 13:52:00,-0.231,-0.998
2,3,2024-09-29 14:52:00,-0.232,-1.000
3,4,2024-09-29 15:52:00,-0.231,-0.998
4,5,2024-09-29 16:52:00,-0.232,-0.998
...,...,...,...,...
8710,8711,2025-09-27 10:52:00,-0.226,-0.854
8711,8712,2025-09-27 11:52:00,-0.226,-0.851
8712,8713,2025-09-27 12:52:00,-0.224,-0.851
8713,8714,2025-09-27 13:52:00,-0.226,-0.849
8714,8715,2025-09-27 14:52:00,-0.226,-0.849

## 4. Splice dataframes together & export files containing full tynitag data timeseries

In [10]:
# Splice Hohsaas boreholes HS1 (BH5) and HS2 (BH6) and export
hs1tt_spliced = splice_timeseries(
    [hs1tt_1st_data, hs1tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "HS1TT_20240808_20250927_spliced.csv",
    file_stem="HS1TT_20240808_20250927_spliced"
)

hs2tt_spliced = splice_timeseries(
    [hs2tt_1st_data, hs2tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "HS2TT_20240808_20250927_spliced.csv",
    file_stem="HS2TT_20240808_20250927_spliced"
)

# Splice Chessjen boreholes CJ1 (BH7) and CJ2 (BH8) and export
cj1tt_spliced = splice_timeseries(
    [cj1tt_1st_data, cj1tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "CJ1TT_20240809_20250808_spliced.csv",
    file_stem="CJ1TT_20240809_20250808_spliced"
)

cj2tt_spliced = splice_timeseries(
    [cj2tt_1st_data, cj2tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "CJ2TT_20240809_20250808_spliced.csv",
    file_stem="CJ2TT_20240809_20250808_spliced"
)

# Splice Glacier de Tortin boreholes GT1 (BH3) and GT2 (BH4) and export
gt1tt_spliced = splice_timeseries(
    [gt1tt_1st_data, gt1tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "GT1TT_20240807_20250723_spliced.csv",
    file_stem="GT1TT_20240807_20250723_spliced"
)

gt2tt_spliced = splice_timeseries(
    [gt2tt_1st_data, gt2tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "GT2TT_20240807_20250723_spliced.csv",
    file_stem="GT2TT_20240807_20250723_spliced"
)

# Splice Sex Rouge boreholes SR1 (BH1) and SR2 (BH2) and export
sr1tt_spliced = splice_timeseries(
    [sr1tt_1st_data, sr1tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "SR1TT_20240806_20250724_spliced.csv",
    file_stem="SR1TT_20240806_20250724_spliced"
) 

sr2tt_spliced = splice_timeseries(
    [sr2tt_1st_data, sr2tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "SR2TT_20240806_20250724_spliced.csv",
    file_stem="SR2TT_20240806_20250724_spliced"
)

# Splice Corvatsch borehole CT2 (BH12) and export
ct2tt_spliced = splice_timeseries(
    [ct2tt_1st_data, ct2tt_2nd_data],
    time_col="TIME",
    out_path=output_path + "CT2TT_20240828_20250905_spliced.csv",
    file_stem="CT2TT_20240828_20250905_spliced"
)

# Splice Alphubel South borehole AH1 (BH10) and export
ah1tt_spliced = splice_timeseries(
    [ah1tt_1st_data, ah1tt_2nd_data, ah1tt_3rd_data],
    time_col="TIME",
    out_path=output_path + "AH1TT_20240821_20250916_spliced.csv",
    file_stem="AH1TT_20240821_20250916_spliced"
)

Warning: found 1 gaps > 1 hour

In [7]:
hs1tt_spliced

,Measurement,TIME,Black Probe Temperature,White Probe Temperature
0,1,2024-08-08 15:28:00,-0.092,-0.139
1,2,2024-08-08 16:28:00,-0.095,-0.143
2,3,2024-08-08 17:28:00,-0.095,-0.143
3,4,2024-08-08 18:28:00,-0.095,-0.143
4,5,2024-08-08 19:28:00,-0.097,-0.143
...,...,...,...,...
9956,9957,2025-09-27 10:52:00,-0.226,-0.854
9957,9958,2025-09-27 11:52:00,-0.226,-0.851
9958,9959,2025-09-27 12:52:00,-0.224,-0.851
9959,9960,2025-09-27 13:52:00,-0.226,-0.849
9960,9961,2025-09-27 14:52:00,-0.226,-0.849